#if !defined(AFX_DBCOMBO_H__FDAE19CF_3586_4130_AD7D_79BC6CDCD4E9__INCLUDED_)
#define AFX_DBCOMBO_H__FDAE19CF_3586_4130_AD7D_79BC6CDCD4E9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture1;
class CRowCursor;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CDBCombo wrapper class

class CDBCombo : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDBCombo)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfaeee760, 0x117e, 0x101b, { 0x89, 0x33, 0x8, 0x0, 0x2b, 0x2f, 0x4f, 0x5a } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetListField();
	void SetListField(LPCTSTR lpszNewValue);
	CString GetBoundText();
	void SetBoundText(LPCTSTR lpszNewValue);
	CString GetBoundColumn();
	void SetBoundColumn(LPCTSTR lpszNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetMousePointer();
	void SetMousePointer(long nNewValue);
	BOOL GetLocked();
	void SetLocked(BOOL bNewValue);
	CPicture1 GetMouseIcon();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	BOOL GetIntegralHeight();
	void SetIntegralHeight(BOOL bNewValue);
	long GetSelStart();
	void SetSelStart(long nNewValue);
	long GetSelLength();
	void SetSelLength(long nNewValue);
	CString GetSelText();
	void SetSelText(LPCTSTR lpszNewValue);
	long GetMatchEntry();
	void SetMatchEntry(long nNewValue);
	VARIANT GetSelectedItem();
	short GetVisibleCount();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CRowCursor GetRowSource();
	void SetRowSource(LPDISPATCH newValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	COleFont GetFont();
	void SetRefFont(LPDISPATCH newValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetMatchedWithList();
	long GetAppearance();
	void SetAppearance(long nNewValue);
	long GetHwnd();
	BOOL GetRightToLeft();
	void SetRightToLeft(BOOL bNewValue);
	long GetOLEDragMode();
	void SetOLEDragMode(long nNewValue);
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	void ReFill();
	VARIANT GetVisibleItems(short nIndex);
	void Refresh();
	void OLEDrag();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DBCOMBO_H__FDAE19CF_3586_4130_AD7D_79BC6CDCD4E9__INCLUDED_)
